# Site settings
title: Wade Robson
#email: wade.robson4@gmail.com
description: "Another OSX Administrator's blog"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://waderobson.ca" # the base hostname & protocol for your site
twitter_username: philspaces
github_username:  waderobson

# Build settings
markdown: kramdown
